# [RAGAs를 이용한 데이터셋 생성](https://docs.ragas.io/en/stable/howtos/customizations/testgenerator/_language_adaptation/#generate)

## install

In [1]:
# !pip install ragas==0.3.5 langchain-openai==0.3.8

## dataset

In [2]:
import pandas as pd

df = pd.read_csv("./download/질병.csv")
df.head()

,video_url,video_id,title,channel,caption
0,https://www.youtube.com/watch?v=8GwNlF44ntY&li...,8GwNlF44ntY,#164 식은땀! 이 정도는 알아두셔야 합니다. : 하정훈의 육아이야기,하정훈의 삐뽀삐뽀 119 소아과 (삐뽀삐뽀 119 소아과),[음악] 안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만 아직도 ...
1,https://www.youtube.com/watch?v=8GwNlF44ntY,8GwNlF44ntY,#164 식은땀! 이 정도는 알아두셔야 합니다. : 하정훈의 육아이야기,하정훈의 삐뽀삐뽀 119 소아과 (삐뽀삐뽀 119 소아과),[음악] 안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만 아직도 ...
2,https://www.youtube.com/watch?v=ZO1ffVTWsJc,ZO1ffVTWsJc,"#158 식중독, 단순 배탈과 다릅니다. 주의사항 알아봅시다: 하정훈의 육아이야기",하정훈의 삐뽀삐뽀 119 소아과 (삐뽀삐뽀 119 소아과),[음악] 안녕하세요 소아청소년과 전문의 과정 입니다 날이 더운 여름이 되면 집중 독...
3,https://www.youtube.com/watch?v=ZZkU79leibA,ZZkU79leibA,#157 햄버거병? 용혈성요독증후군 제대로 알아봅시다,하정훈의 삐뽀삐뽀 119 소아과 (삐뽀삐뽀 119 소아과),[음악] 안녕하세요 서 청순과 전문의 가정입니다 최근 안산의 한 유치원에서 식중독 ...
4,https://www.youtube.com/watch?v=w8BucI0wZYE,w8BucI0wZYE,#139 설사하는 아이 제대로 먹여야 합니다: 하정훈의 육아이야기,하정훈의 삐뽀삐뽀 119 소아과 (삐뽀삐뽀 119 소아과),으 안녕하세요 어화 중 성과 전문의 가져옵니다 예전보다는 많이 줄었지만 아직도 설 ...

### Cleaning Caption

In [3]:
def cleaning_caption(data:str) -> str:
  return data.replace("으 ", "").replace(" 으", "")\
    .replace("아 ", "").replace(" 아", "").replace("[음악]", "").strip()

In [4]:
df['caption'] = df['caption'].map(cleaning_caption)

In [5]:
df.loc[0,['caption']].values

array(['안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간 다 나았는데 어디 약한거닌가 라는 이야기 하시는 분 종종 있습니다 감기 약이라도 먹고 있으면 약이 너무 센 것은닌가 라고 물어보기도 합니다 이번에는 많은 부모들이 고민하고 있는 식은 땀 이라는 것에 대해서 말씀을 드리겠습니다 사람들은 원래 몸에 담이 나게 되어 있죠 사람 몸에는 200만 개가 되는 땅 팀이 있어 땀을 흘리게 되는데 땀 이란 우리 몸 안의 노폐물을 배출하고 체온을 조절하는 역할을 하게 됩니다 적당히 땀을 흘리는 것은 정상입니다 사람마다 차이가 크지만이들은 어른의 피에서 남을 드 많이 걸립니다 게다가이들은 땀을 조절하는 기능이 어른들의 비해서 미숙하기 때문에 땅 세미나는 이 많았 인물이나 성 바닥 발바닥은 평소에도 식사를 하거나 조금 말 힘이 들어도 땀이 송골송골 맺히는 경우가 흔합니다 별다른 문제가 없어도 베개가 땀으로 젖는 경우도 있습니다 물론 감기에 걸리거나 다른 이상이 있는 경우에도 땅 조절하는 기능이 더 떨어져서 남을 과잉생산 하기도 합니다이들은 원래 땀이 많은 보입니다 그런데이가 땀을 많이 흘리면 몸이 허약하다 고 생각하는 부모들이 많은 것이 현실입니다기가 빔닌데도 땀을 많이 흘리니 까 몸이 허약하다 고 몸보신을 해줘야 한다고 말하는 부모도 있습니다 땀을 흘린다고 영양제 먹이는 부모도 많은 것이 현실입니다 부모들이 그렇게도 고민고민 하면서 운이 않은이들이 시킨 다음에 대해서 소청소에 가설은 별로 심각하게 생각하지 않습니다이가 땀을 많이 클리 더라도 열이 없고로 보기에 다른 이상이 없는 경우에는 대개 체계적인 경우라고 생각합니다 특히기가 어릴수록 땀을 많이 흘리게 되고 평소에 땀을 않으니 다가 갑자기 많이 흘리게 되는 경우도 많습니다이들 중에서도 특히 네이는 은니 식은땀을 많이 흘리는 법입니다 그런데 간혹 진짜 문제가 있는 경우도 있습니다 선천성 심장병이 있거나 갑상선 기능 항진증 처럼기의 체력을 소모시키는 병에 걸려도 땀을 많이 흘립니다 구루병 저혈당 수온 증도 핵 황달로 이란 4승 말이 내용 후에 점 같은 듣기만 해도 무시무시한 병들의 걸려도 땀을 많이 걸리지만 이름 병들은 원래 매우 드물고 요 다른 증상으로 병이 있는 것을 의심하지 땀을 많이 흘린다고 이름 병 대로의 심하지는 않습니다 예전에 영양이 부족하던 실 계획처럼 체력을 많이 소모시키는 병에 걸리면 땀을 많이 흘렸던 것은 사실입니다 하지만이들의 경우 결핵이 쉬운 땀이 오리니 되는 경우는 그 이 생각하기 힘듭니다 물론 남을 너무 많이 흘리거나 특정 부위에 땀이 지나치게 많은 경우는 한 번은 소아청소년과 의사 에게 보여서 다른 이상을 없는지 확인하는 것이 안전합니다 일반적으로는 담임니라도 다른 이상이 없다면 너무 걱정하지 말고 수분 충분히 섭취 시키고 잘 닦아주고 옷 자주 가입해서 채운 소실되지 않도록 신경 등 도 써주시면 된다는 거 알2시면 마음 편하실 겁니다 지금 땀 너무 걱정하지 마십시오'],
      dtype=object)

In [7]:
df.head(2)

,video_url,video_id,title,channel,caption
0,https://www.youtube.com/watch?v=8GwNlF44ntY&li...,8GwNlF44ntY,#164 식은땀! 이 정도는 알아두셔야 합니다. : 하정훈의 육아이야기,하정훈의 삐뽀삐뽀 119 소아과 (삐뽀삐뽀 119 소아과),안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간...
1,https://www.youtube.com/watch?v=8GwNlF44ntY,8GwNlF44ntY,#164 식은땀! 이 정도는 알아두셔야 합니다. : 하정훈의 육아이야기,하정훈의 삐뽀삐뽀 119 소아과 (삐뽀삐뽀 119 소아과),안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간...

### Cleaning Title

In [8]:
df.loc[0,['title']].values

array(['#164  식은땀! 이 정도는 알아두셔야 합니다. : 하정훈의 육아이야기'], dtype=object)

In [14]:
def cleaning_title(data:str) -> str:
  title = " ".join(data.split(" ")[1:])

  return title.split(":")[0].strip()

In [15]:
df['title'] = df['title'].map(cleaning_title)

In [16]:
df.loc[0,['title']].values

array(['식은땀! 이 정도는 알아두셔야 합니다.'], dtype=object)

### 학습데이터셋 컬럼 생성

In [17]:
df['title_caption'] = df.apply(
    lambda row: "[title] " + str(row['title']) 
                + " [caption] " + str(row['caption']), axis=1
)

In [18]:
df[['title', 'caption', 'title_caption']].head(2)

,title,caption,title_caption
0,식은땀! 이 정도는 알아두셔야 합니다.,안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간...,[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 ...
1,식은땀! 이 정도는 알아두셔야 합니다.,안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간...,[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 ...

### 필요없는 컬럼 삭제

In [19]:
df.drop(columns=["channel", "video_id"], inplace=True)

In [20]:
df.head(2)

,video_url,title,caption,title_caption
0,https://www.youtube.com/watch?v=8GwNlF44ntY&li...,식은땀! 이 정도는 알아두셔야 합니다.,안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간...,[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 ...
1,https://www.youtube.com/watch?v=8GwNlF44ntY,식은땀! 이 정도는 알아두셔야 합니다.,안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간...,[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 ...

### 학습 데이터셋 저장

In [21]:
df.to_csv("diseases.csv", index=False, header=True)

## Loader

In [23]:
from langchain_community.document_loaders import CSVLoader

# diseases.csv -> caption만 로드 진행할 수 있는 객체
loader = CSVLoader(
    file_path='diseases.csv' # 파일명 
    , source_column='video_url' # 소스 컬럼 
    , content_columns=['title_caption'] # 컨텐츠(학습) 컬럼 
    , encoding="utf-8"
)

In [24]:
docs = loader.load() # load()를 이용해서 데이터 로드 진행..

In [25]:
# df.shape -> (데이터의 수(=유튜브 영상의 수), 컬럼의 수)
len(docs), df.shape

(130, (130, 4))

In [26]:
docs[0].metadata['source']

'https://www.youtube.com/watch?v=8GwNlF44ntY&list=PLC6Msm1YCNw-NJBk4ajBkTeS2rJULiT1b'

In [27]:
docs[0].page_content

'title_caption: [title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간 다 나았는데 어디 약한거닌가 라는 이야기 하시는 분 종종 있습니다 감기 약이라도 먹고 있으면 약이 너무 센 것은닌가 라고 물어보기도 합니다 이번에는 많은 부모들이 고민하고 있는 식은 땀 이라는 것에 대해서 말씀을 드리겠습니다 사람들은 원래 몸에 담이 나게 되어 있죠 사람 몸에는 200만 개가 되는 땅 팀이 있어 땀을 흘리게 되는데 땀 이란 우리 몸 안의 노폐물을 배출하고 체온을 조절하는 역할을 하게 됩니다 적당히 땀을 흘리는 것은 정상입니다 사람마다 차이가 크지만이들은 어른의 피에서 남을 드 많이 걸립니다 게다가이들은 땀을 조절하는 기능이 어른들의 비해서 미숙하기 때문에 땅 세미나는 이 많았 인물이나 성 바닥 발바닥은 평소에도 식사를 하거나 조금 말 힘이 들어도 땀이 송골송골 맺히는 경우가 흔합니다 별다른 문제가 없어도 베개가 땀으로 젖는 경우도 있습니다 물론 감기에 걸리거나 다른 이상이 있는 경우에도 땅 조절하는 기능이 더 떨어져서 남을 과잉생산 하기도 합니다이들은 원래 땀이 많은 보입니다 그런데이가 땀을 많이 흘리면 몸이 허약하다 고 생각하는 부모들이 많은 것이 현실입니다기가 빔닌데도 땀을 많이 흘리니 까 몸이 허약하다 고 몸보신을 해줘야 한다고 말하는 부모도 있습니다 땀을 흘린다고 영양제 먹이는 부모도 많은 것이 현실입니다 부모들이 그렇게도 고민고민 하면서 운이 않은이들이 시킨 다음에 대해서 소청소에 가설은 별로 심각하게 생각하지 않습니다이가 땀을 많이 클리 더라도 열이 없고로 보기에 다른 이상이 없는 경우에는 대개 체계적인 경우라고 생각합니다 특히기가 어릴수록 땀을 많이 흘리게 되고 평소에 땀을 않으니 다가 갑자기 많이 흘리게 되는 경우도 많습니다이들 중에서도 특히 네이는 은니 식은땀을 많이 흘리는 법입니다 그런데 간혹 진짜 문제가 있는 경우도 있습니다 선천성 심장병이 있거나 갑상선 기능 항진증 처럼기의 체력을 소모시키는 병에 걸려도 땀을 많이 흘립니다 구루병 저혈당 수온 증도 핵 황달로 이란 4승 말이 내용 후에 점 같은 듣기만 해도 무시무시한 병들의 걸려도 땀을 많이 걸리지만 이름 병들은 원래 매우 드물고 요 다른 증상으로 병이 있는 것을 의심하지 땀을 많이 흘린다고 이름 병 대로의 심하지는 않습니다 예전에 영양이 부족하던 실 계획처럼 체력을 많이 소모시키는 병에 걸리면 땀을 많이 흘렸던 것은 사실입니다 하지만이들의 경우 결핵이 쉬운 땀이 오리니 되는 경우는 그 이 생각하기 힘듭니다 물론 남을 너무 많이 흘리거나 특정 부위에 땀이 지나치게 많은 경우는 한 번은 소아청소년과 의사 에게 보여서 다른 이상을 없는지 확인하는 것이 안전합니다 일반적으로는 담임니라도 다른 이상이 없다면 너무 걱정하지 말고 수분 충분히 섭취 시키고 잘 닦아주고 옷 자주 가입해서 채운 소실되지 않도록 신경 등 도 써주시면 된다는 거 알2시면 마음 편하실 겁니다 지금 땀 너무 걱정하지 마십시오'

## Model

### [OpenAI API Key](https://platform.openai.com/settings/organization/api-keys)

In [ ]:
import os

# os.environ['OPENAI_API_KEY'] = 'sk-'

In [28]:
from dotenv import load_dotenv 

# .env 파일에 있는 데이터를 환경변수에 등록해주는 함수 
load_dotenv()

True

In [29]:
import os 

api_key = os.getenv("OPENAI_API_KEY")

if api_key:
    print("OpenAI API 키가 설정되었습니다.")
else:
    print("OpenAI API 키가 없어요.")

OpenAI API 키가 설정되었습니다.

## 학습 데이터셋

In [30]:
# Langchain LLM 객체를 ragas가 인식할 수 있게 변형
# Wrapper -> 감싸다. 또는 형변환 된다...
from ragas.llms import LangchainLLMWrapper
# Langchain Embedding model를 ragas가 인식할 수 있게 변형
from ragas.embeddings import LangchainEmbeddingsWrapper
# Langchain에서 인식할 수 있는 OpenaAI LLM 객체
from langchain_openai import ChatOpenAI
# Langchain에서 인식할 수 있는 OpenaAI Embedding model 객체
from langchain_openai import OpenAIEmbeddings

### [문장을 생성하는 LLM](https://platform.openai.com/docs/models)

In [ ]:
# 문장을 생성하는 LLM -> 질문 & 답변 생성을 목적으로...
generator_llm = LangchainLLMWrapper(ChatOpenAI(
    model="gpt-5-mini",
    reasoning_effort="high",        # 논리성 강화
))

### [Embedding model](https://platform.openai.com/docs/guides/embeddings/embedding-models#embedding-models)

In [32]:
# Embedding model -> 문장을 벡터로 변환하는 모델...
generator_embeddings = LangchainEmbeddingsWrapper(
    OpenAIEmbeddings(model="text-embedding-3-small"))

C:\Users\Playdata\AppData\Local\Temp\ipykernel_3432\1077764151.py:2: DeprecationWarning: LangchainEmbeddingsWrapper is deprecated and will be removed in a future version. Use the modern embedding providers instead: embedding_factory('openai', model='text-embedding-3-small', client=openai_client) or from ragas.embeddings import OpenAIEmbeddings, GoogleEmbeddings, HuggingFaceEmbeddings
  generator_embeddings = LangchainEmbeddingsWrapper(

### 페르소나 정의(중요)
> 어떤 질문/답변 쌍을 만들지 정의함

In [39]:
from ragas.testset.persona import Persona

personas = [
    Persona(
        name="pediatrician doctor", # 소아과 의사 선생님
        # 어떤 질문을 생성해야 하는지에 대한 설명
        role_description=""""
        A doctor who explains diseases in an easy-to-understand manner to the general public.
        """,
    ),
]

### 학습용 데이터를 만드는 객체

In [ ]:
from ragas.testset import TestsetGenerator

# 학습용 데이터를 만드는 객체
generator = TestsetGenerator(
    llm=generator_llm, embedding_model=generator_embeddings, persona_list=personas
)

In [40]:
from ragas.testset.transforms.extractors.llm_based import NERExtractor, SummaryExtractor, TitleExtractor

# transforms = [SummaryExtractor(), NERExtractor(), TitleExtractor()]
transforms = [NERExtractor()]

In [42]:
from ragas.testset.synthesizers.single_hop.specific import (
    SingleHopSpecificQuerySynthesizer
)

distribution = [
    (SingleHopSpecificQuerySynthesizer(llm=generator_llm), 1.0),
]

for query, _ in distribution:
    prompts = await query.adapt_prompts("korean", llm=generator_llm)
    query.set_prompts(**prompts)

### 학습용 데이터셋 생성

In [43]:
dataset = generator.generate_with_langchain_docs(
    docs[:],
    testset_size=50, # 총 몇개의 질문/답변 쌍을 만들지
    transforms=transforms,
    query_distribution=distribution,
)

Applying NERExtractor:   0%|          | 0/130 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/1 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/50 [00:00<?, ?it/s]

## 생성된 데이터셋 확인

In [67]:
eval_dataset = dataset.to_evaluation_dataset()

In [68]:
print("Query:", eval_dataset[0].user_input)
print("Reference:", eval_dataset[0].reference)

Query: 갑상선 기능 항진증이 어린이에게 미치는 영향은 무엇인가요?
Reference: 갑상선 기능 항진증은 어린이가 체력을 소모시키는 병으로, 이로 인해 땀을 많이 흘릴 수 있습니다. 그러나 땀을 많이 흘린다고 해서 반드시 심각한 문제가 있는 것은 아니며, 다른 이상이 없는 경우에는 대개 체계적인 경우로 생각할 수 있습니다.

In [69]:
# 생성된 테스트셋을 pandas DataFrame으로 변환
test_df = eval_dataset.to_pandas()
test_df.shape

(50, 3)

In [70]:
test_df.head(2)

,user_input,reference_contexts,reference
0,갑상선 기능 항진증이 어린이에게 미치는 영향은 무엇인가요?,[title_caption: [title] 식은땀! 이 정도는 알아두셔야 합니다. ...,"갑상선 기능 항진증은 어린이가 체력을 소모시키는 병으로, 이로 인해 땀을 많이 흘릴..."
1,구루병이 땀을 많이 흘리는 것과 어떤 관계가 있나요?,[title_caption: [title] 식은땀! 이 정도는 알아두셔야 합니다. ...,구루병은 땀을 많이 흘리는 원인 중 하나일 수 있습니다. 그러나 구루병은 매우 드물...

### reference_video_url 추가하기

In [71]:
test_df.loc[0,['reference_contexts']].values[0][0].replace("title_caption: ", "")

'[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간 다 나았는데 어디 약한거닌가 라는 이야기 하시는 분 종종 있습니다 감기 약이라도 먹고 있으면 약이 너무 센 것은닌가 라고 물어보기도 합니다 이번에는 많은 부모들이 고민하고 있는 식은 땀 이라는 것에 대해서 말씀을 드리겠습니다 사람들은 원래 몸에 담이 나게 되어 있죠 사람 몸에는 200만 개가 되는 땅 팀이 있어 땀을 흘리게 되는데 땀 이란 우리 몸 안의 노폐물을 배출하고 체온을 조절하는 역할을 하게 됩니다 적당히 땀을 흘리는 것은 정상입니다 사람마다 차이가 크지만이들은 어른의 피에서 남을 드 많이 걸립니다 게다가이들은 땀을 조절하는 기능이 어른들의 비해서 미숙하기 때문에 땅 세미나는 이 많았 인물이나 성 바닥 발바닥은 평소에도 식사를 하거나 조금 말 힘이 들어도 땀이 송골송골 맺히는 경우가 흔합니다 별다른 문제가 없어도 베개가 땀으로 젖는 경우도 있습니다 물론 감기에 걸리거나 다른 이상이 있는 경우에도 땅 조절하는 기능이 더 떨어져서 남을 과잉생산 하기도 합니다이들은 원래 땀이 많은 보입니다 그런데이가 땀을 많이 흘리면 몸이 허약하다 고 생각하는 부모들이 많은 것이 현실입니다기가 빔닌데도 땀을 많이 흘리니 까 몸이 허약하다 고 몸보신을 해줘야 한다고 말하는 부모도 있습니다 땀을 흘린다고 영양제 먹이는 부모도 많은 것이 현실입니다 부모들이 그렇게도 고민고민 하면서 운이 않은이들이 시킨 다음에 대해서 소청소에 가설은 별로 심각하게 생각하지 않습니다이가 땀을 많이 클리 더라도 열이 없고로 보기에 다른 이상이 없는 경우에는 대개 체계적인 경우라고 생각합니다 특히기가 어릴수록 땀을 많이 흘리게 되고 평소에 땀을 않으니 다가 갑자기 많이 흘리게 되는 경우도 많습니다이들 중에서도 특히 네이는 은니 식은땀을 많이 흘리는 법입니다 그런데 간혹 진짜 문제가 있는 경우도 있습니다 선천성 심장병이 있거나 갑상선 기능 항진증 처럼기의 체력을 소모시키는 병에 걸려도 땀을 많이 흘립니다 구루병 저혈당 수온 증도 핵 황달로 이란 4승 말이 내용 후에 점 같은 듣기만 해도 무시무시한 병들의 걸려도 땀을 많이 걸리지만 이름 병들은 원래 매우 드물고 요 다른 증상으로 병이 있는 것을 의심하지 땀을 많이 흘린다고 이름 병 대로의 심하지는 않습니다 예전에 영양이 부족하던 실 계획처럼 체력을 많이 소모시키는 병에 걸리면 땀을 많이 흘렸던 것은 사실입니다 하지만이들의 경우 결핵이 쉬운 땀이 오리니 되는 경우는 그 이 생각하기 힘듭니다 물론 남을 너무 많이 흘리거나 특정 부위에 땀이 지나치게 많은 경우는 한 번은 소아청소년과 의사 에게 보여서 다른 이상을 없는지 확인하는 것이 안전합니다 일반적으로는 담임니라도 다른 이상이 없다면 너무 걱정하지 말고 수분 충분히 섭취 시키고 잘 닦아주고 옷 자주 가입해서 채운 소실되지 않도록 신경 등 도 써주시면 된다는 거 알2시면 마음 편하실 겁니다 지금 땀 너무 걱정하지 마십시오'

In [72]:
# df[['video_url', 'title_caption']].head(2)
df.loc[0,['title_caption']].values[0]

'[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간 다 나았는데 어디 약한거닌가 라는 이야기 하시는 분 종종 있습니다 감기 약이라도 먹고 있으면 약이 너무 센 것은닌가 라고 물어보기도 합니다 이번에는 많은 부모들이 고민하고 있는 식은 땀 이라는 것에 대해서 말씀을 드리겠습니다 사람들은 원래 몸에 담이 나게 되어 있죠 사람 몸에는 200만 개가 되는 땅 팀이 있어 땀을 흘리게 되는데 땀 이란 우리 몸 안의 노폐물을 배출하고 체온을 조절하는 역할을 하게 됩니다 적당히 땀을 흘리는 것은 정상입니다 사람마다 차이가 크지만이들은 어른의 피에서 남을 드 많이 걸립니다 게다가이들은 땀을 조절하는 기능이 어른들의 비해서 미숙하기 때문에 땅 세미나는 이 많았 인물이나 성 바닥 발바닥은 평소에도 식사를 하거나 조금 말 힘이 들어도 땀이 송골송골 맺히는 경우가 흔합니다 별다른 문제가 없어도 베개가 땀으로 젖는 경우도 있습니다 물론 감기에 걸리거나 다른 이상이 있는 경우에도 땅 조절하는 기능이 더 떨어져서 남을 과잉생산 하기도 합니다이들은 원래 땀이 많은 보입니다 그런데이가 땀을 많이 흘리면 몸이 허약하다 고 생각하는 부모들이 많은 것이 현실입니다기가 빔닌데도 땀을 많이 흘리니 까 몸이 허약하다 고 몸보신을 해줘야 한다고 말하는 부모도 있습니다 땀을 흘린다고 영양제 먹이는 부모도 많은 것이 현실입니다 부모들이 그렇게도 고민고민 하면서 운이 않은이들이 시킨 다음에 대해서 소청소에 가설은 별로 심각하게 생각하지 않습니다이가 땀을 많이 클리 더라도 열이 없고로 보기에 다른 이상이 없는 경우에는 대개 체계적인 경우라고 생각합니다 특히기가 어릴수록 땀을 많이 흘리게 되고 평소에 땀을 않으니 다가 갑자기 많이 흘리게 되는 경우도 많습니다이들 중에서도 특히 네이는 은니 식은땀을 많이 흘리는 법입니다 그런데 간혹 진짜 문제가 있는 경우도 있습니다 선천성 심장병이 있거나 갑상선 기능 항진증 처럼기의 체력을 소모시키는 병에 걸려도 땀을 많이 흘립니다 구루병 저혈당 수온 증도 핵 황달로 이란 4승 말이 내용 후에 점 같은 듣기만 해도 무시무시한 병들의 걸려도 땀을 많이 걸리지만 이름 병들은 원래 매우 드물고 요 다른 증상으로 병이 있는 것을 의심하지 땀을 많이 흘린다고 이름 병 대로의 심하지는 않습니다 예전에 영양이 부족하던 실 계획처럼 체력을 많이 소모시키는 병에 걸리면 땀을 많이 흘렸던 것은 사실입니다 하지만이들의 경우 결핵이 쉬운 땀이 오리니 되는 경우는 그 이 생각하기 힘듭니다 물론 남을 너무 많이 흘리거나 특정 부위에 땀이 지나치게 많은 경우는 한 번은 소아청소년과 의사 에게 보여서 다른 이상을 없는지 확인하는 것이 안전합니다 일반적으로는 담임니라도 다른 이상이 없다면 너무 걱정하지 말고 수분 충분히 섭취 시키고 잘 닦아주고 옷 자주 가입해서 채운 소실되지 않도록 신경 등 도 써주시면 된다는 거 알2시면 마음 편하실 겁니다 지금 땀 너무 걱정하지 마십시오'

In [73]:
test_df['reference_title_caption'] = test_df['reference_contexts'].map(
    lambda x: x[0].replace("title_caption: ", "").strip()
)

test_df[['reference_title_caption', 'reference_contexts']].head(2)

,reference_title_caption,reference_contexts
0,[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 ...,[title_caption: [title] 식은땀! 이 정도는 알아두셔야 합니다. ...
1,[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 ...,[title_caption: [title] 식은땀! 이 정도는 알아두셔야 합니다. ...

In [74]:
test_df = test_df.merge(
    right=df[['video_url', 'title_caption']], how='inner',
    left_on="reference_title_caption", right_on="title_caption"
)

In [77]:
test_df.rename(
    columns={
        "video_url": "reference_video_url"
    }, inplace= True
)

In [78]:
test_df[['user_input', 'reference', 'reference_video_url']].head()

,user_input,reference,reference_video_url
0,갑상선 기능 항진증이 어린이에게 미치는 영향은 무엇인가요?,"갑상선 기능 항진증은 어린이가 체력을 소모시키는 병으로, 이로 인해 땀을 많이 흘릴...",https://www.youtube.com/watch?v=8GwNlF44ntY&li...
1,갑상선 기능 항진증이 어린이에게 미치는 영향은 무엇인가요?,"갑상선 기능 항진증은 어린이가 체력을 소모시키는 병으로, 이로 인해 땀을 많이 흘릴...",https://www.youtube.com/watch?v=8GwNlF44ntY
2,구루병이 땀을 많이 흘리는 것과 어떤 관계가 있나요?,구루병은 땀을 많이 흘리는 원인 중 하나일 수 있습니다. 그러나 구루병은 매우 드물...,https://www.youtube.com/watch?v=8GwNlF44ntY&li...
3,구루병이 땀을 많이 흘리는 것과 어떤 관계가 있나요?,구루병은 땀을 많이 흘리는 원인 중 하나일 수 있습니다. 그러나 구루병은 매우 드물...,https://www.youtube.com/watch?v=8GwNlF44ntY
4,허니 햄버거 병이란 무엇인가요?,허니 햄버거 병은 연결성 여덕 저온 같은 심각한 합병증이 동반되는 식중독의 일종입니...,https://www.youtube.com/watch?v=ZO1ffVTWsJc

In [83]:
test_df = test_df[['user_input', 'reference', 'reference_video_url']]
print(f"befer: {test_df.shape}")
test_df.drop_duplicates(inplace=True, subset=['user_input', 'reference'])
print(f"after: {test_df.shape}")

befer: (52, 3)
after: (50, 3)

### 저장하기

In [84]:
test_df.to_csv("df_train.csv", index=False, header=True)