# [RAGAs를 이용한 데이터셋 생성](https://docs.ragas.io/en/stable/howtos/customizations/testgenerator/_language_adaptation/#generate)

## dataset

In [3]:
import pandas as pd

df = pd.read_csv("./data/download/질병.csv")

print(f"(전체 데이터 수, 전체 컬럼 수): {df.shape}")
df.head(2)

(전체 데이터 수, 전체 컬럼 수): (130, 5)

,video_url,video_id,title,channel,caption
0,https://www.youtube.com/watch?v=8GwNlF44ntY&li...,8GwNlF44ntY,#164 식은땀! 이 정도는 알아두셔야 합니다. : 하정훈의 육아이야기,하정훈의 삐뽀삐뽀 119 소아과 (삐뽀삐뽀 119 소아과),[음악] 안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만 아직도 ...
1,https://www.youtube.com/watch?v=8GwNlF44ntY,8GwNlF44ntY,#164 식은땀! 이 정도는 알아두셔야 합니다. : 하정훈의 육아이야기,하정훈의 삐뽀삐뽀 119 소아과 (삐뽀삐뽀 119 소아과),[음악] 안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만 아직도 ...

### Drop duplicates

In [4]:
df.drop_duplicates(inplace=True, subset=['video_id'])

print(f"(전체 데이터 수, 전체 컬럼 수): {df.shape}")

(전체 데이터 수, 전체 컬럼 수): (129, 5)

### Cleaning Caption

In [ ]:
def cleaning_caption(data:str) -> str:
  return data.replace(" 으 ", "").replace(" 아 ", "")\
    .replace("[음악]", "").replace("[박수]", "").strip()

In [6]:
df['caption'] = df['caption'].map(cleaning_caption)

In [7]:
df.loc[0,['caption']].values

array(['안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간 다 나았는데 어디 약한거닌가 라는 이야기 하시는 분 종종 있습니다 감기 약이라도 먹고 있으면 약이 너무 센 것은닌가 라고 물어보기도 합니다 이번에는 많은 부모들이 고민하고 있는 식은 땀 이라는 것에 대해서 말씀을 드리겠습니다 사람들은 원래 몸에 담이 나게 되어 있죠 사람 몸에는 200만 개가 되는 땅 팀이 있어 땀을 흘리게 되는데 땀 이란 우리 몸 안의 노폐물을 배출하고 체온을 조절하는 역할을 하게 됩니다 적당히 땀을 흘리는 것은 정상입니다 사람마다 차이가 크지만이들은 어른의 피에서 남을 드 많이 걸립니다 게다가이들은 땀을 조절하는 기능이 어른들의 비해서 미숙하기 때문에 땅 세미나는 이 많았 인물이나 성 바닥 발바닥은 평소에도 식사를 하거나 조금 말 힘이 들어도 땀이 송골송골 맺히는 경우가 흔합니다 별다른 문제가 없어도 베개가 땀으로 젖는 경우도 있습니다 물론 감기에 걸리거나 다른 이상이 있는 경우에도 땅 조절하는 기능이 더 떨어져서 남을 과잉생산 하기도 합니다이들은 원래 땀이 많은 보입니다 그런데이가 땀을 많이 흘리면 몸이 허약하다 고 생각하는 부모들이 많은 것이 현실입니다기가 빔닌데도 땀을 많이 흘리니 까 몸이 허약하다 고 몸보신을 해줘야 한다고 말하는 부모도 있습니다 땀을 흘린다고 영양제 먹이는 부모도 많은 것이 현실입니다 부모들이 그렇게도 고민고민 하면서 운이 않은이들이 시킨 다음에 대해서 소청소에 가설은 별로 심각하게 생각하지 않습니다이가 땀을 많이 클리 더라도 열이 없고로 보기에 다른 이상이 없는 경우에는 대개 체계적인 경우라고 생각합니다 특히기가 어릴수록 땀을 많이 흘리게 되고 평소에 땀을 않으니 다가 갑자기 많이 흘리게 되는 경우도 많습니다이들 중에서도 특히 네이는 은니 식은땀을 많이 흘리는 법입니다 그런데 간혹 진짜 문제가 있는 경우도 있습니다 선천성 심장병이 있거나 갑상선 기능 항진증 처럼기의 체력을 소모시키는 병에 걸려도 땀을 많이 흘립니다 구루병 저혈당 수온 증도 핵 황달로 이란 4승 말이 내용 후에 점 같은 듣기만 해도 무시무시한 병들의 걸려도 땀을 많이 걸리지만 이름 병들은 원래 매우 드물고 요 다른 증상으로 병이 있는 것을 의심하지 땀을 많이 흘린다고 이름 병 대로의 심하지는 않습니다 예전에 영양이 부족하던 실 계획처럼 체력을 많이 소모시키는 병에 걸리면 땀을 많이 흘렸던 것은 사실입니다 하지만이들의 경우 결핵이 쉬운 땀이 오리니 되는 경우는 그 이 생각하기 힘듭니다 물론 남을 너무 많이 흘리거나 특정 부위에 땀이 지나치게 많은 경우는 한 번은 소아청소년과 의사 에게 보여서 다른 이상을 없는지 확인하는 것이 안전합니다 일반적으로는 담임니라도 다른 이상이 없다면 너무 걱정하지 말고 수분 충분히 섭취 시키고 잘 닦아주고 옷 자주 가입해서 채운 소실되지 않도록 신경 등 도 써주시면 된다는 거 알2시면 마음 편하실 겁니다 지금 땀 너무 걱정하지 마십시오'],
      dtype=object)

In [8]:
df.head(2)

,video_url,video_id,title,channel,caption
0,https://www.youtube.com/watch?v=8GwNlF44ntY&li...,8GwNlF44ntY,#164 식은땀! 이 정도는 알아두셔야 합니다. : 하정훈의 육아이야기,하정훈의 삐뽀삐뽀 119 소아과 (삐뽀삐뽀 119 소아과),안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간...
2,https://www.youtube.com/watch?v=ZO1ffVTWsJc,ZO1ffVTWsJc,"#158 식중독, 단순 배탈과 다릅니다. 주의사항 알아봅시다: 하정훈의 육아이야기",하정훈의 삐뽀삐뽀 119 소아과 (삐뽀삐뽀 119 소아과),안녕하세요 소아청소년과 전문의 과정 입니다 날이 더운 여름이 되면 집중 독이 많이 ...

### Cleaning Title

In [9]:
df.loc[0,['title']].values

array(['#164  식은땀! 이 정도는 알아두셔야 합니다. : 하정훈의 육아이야기'], dtype=object)

In [ ]:
import re

def cleaning_title(data:str) -> str:
  title = re.sub(r"#\d+", "", data).strip()
  
  return title.split(":")[0].strip()

In [11]:
df['title'] = df['title'].map(cleaning_title)

In [12]:
df.loc[0,['title']].values

array(['식은땀! 이 정도는 알아두셔야 합니다.'], dtype=object)

### 학습데이터셋 컬럼 생성

In [13]:
df['title_caption'] = df.apply(
    lambda row: "[title] " + str(row['title']) 
                + " [caption] " + str(row['caption']), axis=1
)

In [14]:
df[['title', 'caption', 'title_caption']].head(2)

,title,caption,title_caption
0,식은땀! 이 정도는 알아두셔야 합니다.,안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간...,[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 ...
2,"식중독, 단순 배탈과 다릅니다. 주의사항 알아봅시다",안녕하세요 소아청소년과 전문의 과정 입니다 날이 더운 여름이 되면 집중 독이 많이 ...,"[title] 식중독, 단순 배탈과 다릅니다. 주의사항 알아봅시다 [caption]..."

### 필요없는 컬럼 삭제

In [15]:
df.drop(columns=["channel", "video_id"], inplace=True)

In [16]:
df.head(2)

,video_url,title,caption,title_caption
0,https://www.youtube.com/watch?v=8GwNlF44ntY&li...,식은땀! 이 정도는 알아두셔야 합니다.,안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간...,[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 ...
2,https://www.youtube.com/watch?v=ZO1ffVTWsJc,"식중독, 단순 배탈과 다릅니다. 주의사항 알아봅시다",안녕하세요 소아청소년과 전문의 과정 입니다 날이 더운 여름이 되면 집중 독이 많이 ...,"[title] 식중독, 단순 배탈과 다릅니다. 주의사항 알아봅시다 [caption]..."

### 학습 데이터셋 저장

In [17]:
df.to_csv("./data/cleaning/illnesses.csv", index=False, header=True)

## Loader

In [18]:
from langchain_community.document_loaders import CSVLoader

# illnesses.csv -> caption만 로드 진행할 수 있는 객체
loader = CSVLoader(
    file_path="./data/cleaning/illnesses.csv" # 파일명 
    , source_column='video_url' # 소스 컬럼 
    , content_columns=['title_caption'] # 컨텐츠(학습) 컬럼 
    , encoding="utf-8"
)

In [19]:
docs = loader.load() # load()를 이용해서 데이터 로드 진행..

In [20]:
# df.shape -> (데이터의 수(=유튜브 영상의 수), 컬럼의 수)
len(docs), df.shape

(129, (129, 4))

In [21]:
docs[0].metadata['source']

'https://www.youtube.com/watch?v=8GwNlF44ntY&list=PLC6Msm1YCNw-NJBk4ajBkTeS2rJULiT1b'

In [22]:
docs[0].page_content

'title_caption: [title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간 다 나았는데 어디 약한거닌가 라는 이야기 하시는 분 종종 있습니다 감기 약이라도 먹고 있으면 약이 너무 센 것은닌가 라고 물어보기도 합니다 이번에는 많은 부모들이 고민하고 있는 식은 땀 이라는 것에 대해서 말씀을 드리겠습니다 사람들은 원래 몸에 담이 나게 되어 있죠 사람 몸에는 200만 개가 되는 땅 팀이 있어 땀을 흘리게 되는데 땀 이란 우리 몸 안의 노폐물을 배출하고 체온을 조절하는 역할을 하게 됩니다 적당히 땀을 흘리는 것은 정상입니다 사람마다 차이가 크지만이들은 어른의 피에서 남을 드 많이 걸립니다 게다가이들은 땀을 조절하는 기능이 어른들의 비해서 미숙하기 때문에 땅 세미나는 이 많았 인물이나 성 바닥 발바닥은 평소에도 식사를 하거나 조금 말 힘이 들어도 땀이 송골송골 맺히는 경우가 흔합니다 별다른 문제가 없어도 베개가 땀으로 젖는 경우도 있습니다 물론 감기에 걸리거나 다른 이상이 있는 경우에도 땅 조절하는 기능이 더 떨어져서 남을 과잉생산 하기도 합니다이들은 원래 땀이 많은 보입니다 그런데이가 땀을 많이 흘리면 몸이 허약하다 고 생각하는 부모들이 많은 것이 현실입니다기가 빔닌데도 땀을 많이 흘리니 까 몸이 허약하다 고 몸보신을 해줘야 한다고 말하는 부모도 있습니다 땀을 흘린다고 영양제 먹이는 부모도 많은 것이 현실입니다 부모들이 그렇게도 고민고민 하면서 운이 않은이들이 시킨 다음에 대해서 소청소에 가설은 별로 심각하게 생각하지 않습니다이가 땀을 많이 클리 더라도 열이 없고로 보기에 다른 이상이 없는 경우에는 대개 체계적인 경우라고 생각합니다 특히기가 어릴수록 땀을 많이 흘리게 되고 평소에 땀을 않으니 다가 갑자기 많이 흘리게 되는 경우도 많습니다이들 중에서도 특히 네이는 은니 식은땀을 많이 흘리는 법입니다 그런데 간혹 진짜 문제가 있는 경우도 있습니다 선천성 심장병이 있거나 갑상선 기능 항진증 처럼기의 체력을 소모시키는 병에 걸려도 땀을 많이 흘립니다 구루병 저혈당 수온 증도 핵 황달로 이란 4승 말이 내용 후에 점 같은 듣기만 해도 무시무시한 병들의 걸려도 땀을 많이 걸리지만 이름 병들은 원래 매우 드물고 요 다른 증상으로 병이 있는 것을 의심하지 땀을 많이 흘린다고 이름 병 대로의 심하지는 않습니다 예전에 영양이 부족하던 실 계획처럼 체력을 많이 소모시키는 병에 걸리면 땀을 많이 흘렸던 것은 사실입니다 하지만이들의 경우 결핵이 쉬운 땀이 오리니 되는 경우는 그 이 생각하기 힘듭니다 물론 남을 너무 많이 흘리거나 특정 부위에 땀이 지나치게 많은 경우는 한 번은 소아청소년과 의사 에게 보여서 다른 이상을 없는지 확인하는 것이 안전합니다 일반적으로는 담임니라도 다른 이상이 없다면 너무 걱정하지 말고 수분 충분히 섭취 시키고 잘 닦아주고 옷 자주 가입해서 채운 소실되지 않도록 신경 등 도 써주시면 된다는 거 알2시면 마음 편하실 겁니다 지금 땀 너무 걱정하지 마십시오'

## Model

### [OpenAI API Key](https://platform.openai.com/settings/organization/api-keys)

In [23]:
from dotenv import load_dotenv 

# .env 파일에 있는 데이터를 환경변수에 등록해주는 함수 
load_dotenv()

True

## 학습 데이터셋

### [문장을 생성하는 LLM](https://platform.openai.com/docs/models)

In [24]:
# Langchain LLM 객체를 ragas가 인식할 수 있게 변형
# Wrapper -> 감싸다. 또는 형변환 된다...
from ragas.llms import LangchainLLMWrapper
# Langchain에서 인식할 수 있는 OpenaAI LLM 객체
from langchain_openai import ChatOpenAI

# 문장을 생성하는 LLM -> 질문 & 답변 생성을 목적으로...
generator_llm = LangchainLLMWrapper(ChatOpenAI(
    model="gpt-4o-mini"
))

C:\Users\Playdata\AppData\Local\Temp\ipykernel_15336\211073525.py:8: DeprecationWarning: LangchainLLMWrapper is deprecated and will be removed in a future version. Use llm_factory instead: from openai import OpenAI; from ragas.llms import llm_factory; llm = llm_factory('gpt-4o-mini', client=OpenAI(api_key='...'))
  generator_llm = LangchainLLMWrapper(ChatOpenAI(

### [Embedding model](https://platform.openai.com/docs/guides/embeddings/embedding-models#embedding-models)

In [25]:
# RAGAs의 최신 OpenAIEmbeddings 사용 (client 필요)
from ragas.embeddings import OpenAIEmbeddings
from openai import OpenAI

# Embedding model -> 문장을 벡터로 변환하는 모델...
generator_embeddings = OpenAIEmbeddings(
    # OpenAI client 생성 (환경변수의 OPENAI_API_KEY를 자동으로 사용)
    client=OpenAI(),
    model="text-embedding-3-small"
)

### 페르소나 정의(중요)
> 어떤 질문/답변 쌍을 만들지 정의함

In [26]:
from ragas.testset.persona import Persona

personas = [
    Persona(
        name="pediatrician doctor", # 소아과 의사 선생님
        # 일반 대중이 이해하기 쉽게 질병을 설명해주는 의사
        role_description=""""
        You are a pediatrician who explains childhood and toddler illnesses clearly, accurately, and in an easy-to-understand way for parents and caregivers.
        """,
    ),
]

### 학습용 데이터를 만드는 객체

In [27]:
from ragas.testset import TestsetGenerator

# 학습용 데이터를 만드는 객체
generator = TestsetGenerator(
    llm=generator_llm, embedding_model=generator_embeddings, 
    persona_list=personas
)

NERExtractor: 
> RAG 평가용 테스트셋 생성 시, 문서에 등장하는 핵심 엔티티를 뽑아 질문을 자동 생성하는 클래스입니다.

In [28]:
from ragas.testset.transforms.extractors.llm_based import NERExtractor

transforms = [NERExtractor(llm=generator_llm)]

SingleHopSpecificQuerySynthesizer
> Ragas의 테스트셋 생성 기능에서, 단일 문서 기반(single-hop)으로 “특정하고 구체적인 질문”을 자동 생성하는 Synthesizer 클래스입니다.

In [29]:
from ragas.testset.synthesizers.single_hop.specific import (
    SingleHopSpecificQuerySynthesizer
)

distribution = [
    (SingleHopSpecificQuerySynthesizer(llm=generator_llm), 1.0),
]

for query, _ in distribution:
    prompts = await query.adapt_prompts("korean", llm=generator_llm)
    query.set_prompts(**prompts)

### 학습용 데이터셋 생성

In [30]:
dataset = generator.generate_with_langchain_docs(
    docs[:],
    testset_size=600, # 총 몇개의 질문/답변 쌍을 만들지
    transforms=transforms,
    query_distribution=distribution,
)

Applying NERExtractor:   0%|          | 0/129 [00:00<?, ?it/s]

Generating Scenarios:   0%|          | 0/1 [00:00<?, ?it/s]

Generating Samples:   0%|          | 0/600 [00:00<?, ?it/s]

## 생성된 데이터셋 확인

In [31]:
eval_dataset = dataset.to_evaluation_dataset()

In [32]:
print("Query:", eval_dataset[0].user_input)
print("Reference:", eval_dataset[0].reference)

Query: 선천성 심장병이 있는 아동은 식은땀을 많이 흘릴 수 있나요?
Reference: 네, 선천성 심장병이 있는 아동은 땀을 많이 흘릴 수 있습니다. 이는 체력을 소모시키는 병에 걸렸을 때 나타나는 증상 중 하나입니다.

In [33]:
# 생성된 테스트셋을 pandas DataFrame으로 변환
eval_df = eval_dataset.to_pandas()
eval_df.shape

(600, 6)

In [34]:
eval_df.head(2)

,user_input,reference_contexts,reference,persona_name,query_style,query_length
0,선천성 심장병이 있는 아동은 식은땀을 많이 흘릴 수 있나요?,[title_caption: [title] 식은땀! 이 정도는 알아두셔야 합니다. ...,"네, 선천성 심장병이 있는 아동은 땀을 많이 흘릴 수 있습니다. 이는 체력을 소모시...",pediatrician doctor,WEB_SEARCH_LIKE,MEDIUM
1,감기가 있는 어린이가 식은땀을 흘리는 이유는 무엇인가요?,[title_caption: [title] 식은땀! 이 정도는 알아두셔야 합니다. ...,감기에 걸리면 땀을 조절하는 기능이 떨어져서 땀을 과잉 생산할 수 있습니다. 특히 ...,pediatrician doctor,WEB_SEARCH_LIKE,LONG

### reference_video_url 추가하기

In [35]:
eval_df.loc[0,['reference_contexts']].values[0][0].replace("title_caption: ", "")

'[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간 다 나았는데 어디 약한거닌가 라는 이야기 하시는 분 종종 있습니다 감기 약이라도 먹고 있으면 약이 너무 센 것은닌가 라고 물어보기도 합니다 이번에는 많은 부모들이 고민하고 있는 식은 땀 이라는 것에 대해서 말씀을 드리겠습니다 사람들은 원래 몸에 담이 나게 되어 있죠 사람 몸에는 200만 개가 되는 땅 팀이 있어 땀을 흘리게 되는데 땀 이란 우리 몸 안의 노폐물을 배출하고 체온을 조절하는 역할을 하게 됩니다 적당히 땀을 흘리는 것은 정상입니다 사람마다 차이가 크지만이들은 어른의 피에서 남을 드 많이 걸립니다 게다가이들은 땀을 조절하는 기능이 어른들의 비해서 미숙하기 때문에 땅 세미나는 이 많았 인물이나 성 바닥 발바닥은 평소에도 식사를 하거나 조금 말 힘이 들어도 땀이 송골송골 맺히는 경우가 흔합니다 별다른 문제가 없어도 베개가 땀으로 젖는 경우도 있습니다 물론 감기에 걸리거나 다른 이상이 있는 경우에도 땅 조절하는 기능이 더 떨어져서 남을 과잉생산 하기도 합니다이들은 원래 땀이 많은 보입니다 그런데이가 땀을 많이 흘리면 몸이 허약하다 고 생각하는 부모들이 많은 것이 현실입니다기가 빔닌데도 땀을 많이 흘리니 까 몸이 허약하다 고 몸보신을 해줘야 한다고 말하는 부모도 있습니다 땀을 흘린다고 영양제 먹이는 부모도 많은 것이 현실입니다 부모들이 그렇게도 고민고민 하면서 운이 않은이들이 시킨 다음에 대해서 소청소에 가설은 별로 심각하게 생각하지 않습니다이가 땀을 많이 클리 더라도 열이 없고로 보기에 다른 이상이 없는 경우에는 대개 체계적인 경우라고 생각합니다 특히기가 어릴수록 땀을 많이 흘리게 되고 평소에 땀을 않으니 다가 갑자기 많이 흘리게 되는 경우도 많습니다이들 중에서도 특히 네이는 은니 식은땀을 많이 흘리는 법입니다 그런데 간혹 진짜 문제가 있는 경우도 있습니다 선천성 심장병이 있거나 갑상선 기능 항진증 처럼기의 체력을 소모시키는 병에 걸려도 땀을 많이 흘립니다 구루병 저혈당 수온 증도 핵 황달로 이란 4승 말이 내용 후에 점 같은 듣기만 해도 무시무시한 병들의 걸려도 땀을 많이 걸리지만 이름 병들은 원래 매우 드물고 요 다른 증상으로 병이 있는 것을 의심하지 땀을 많이 흘린다고 이름 병 대로의 심하지는 않습니다 예전에 영양이 부족하던 실 계획처럼 체력을 많이 소모시키는 병에 걸리면 땀을 많이 흘렸던 것은 사실입니다 하지만이들의 경우 결핵이 쉬운 땀이 오리니 되는 경우는 그 이 생각하기 힘듭니다 물론 남을 너무 많이 흘리거나 특정 부위에 땀이 지나치게 많은 경우는 한 번은 소아청소년과 의사 에게 보여서 다른 이상을 없는지 확인하는 것이 안전합니다 일반적으로는 담임니라도 다른 이상이 없다면 너무 걱정하지 말고 수분 충분히 섭취 시키고 잘 닦아주고 옷 자주 가입해서 채운 소실되지 않도록 신경 등 도 써주시면 된다는 거 알2시면 마음 편하실 겁니다 지금 땀 너무 걱정하지 마십시오'

In [36]:
# df[['video_url', 'title_caption']].head(2)
df.loc[0,['title_caption']].values[0]

'[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 소아청소년과 전문의 가져옵니다 이제는 많이 줄긴 했지만직도 우리기가 시간 다 나았는데 어디 약한거닌가 라는 이야기 하시는 분 종종 있습니다 감기 약이라도 먹고 있으면 약이 너무 센 것은닌가 라고 물어보기도 합니다 이번에는 많은 부모들이 고민하고 있는 식은 땀 이라는 것에 대해서 말씀을 드리겠습니다 사람들은 원래 몸에 담이 나게 되어 있죠 사람 몸에는 200만 개가 되는 땅 팀이 있어 땀을 흘리게 되는데 땀 이란 우리 몸 안의 노폐물을 배출하고 체온을 조절하는 역할을 하게 됩니다 적당히 땀을 흘리는 것은 정상입니다 사람마다 차이가 크지만이들은 어른의 피에서 남을 드 많이 걸립니다 게다가이들은 땀을 조절하는 기능이 어른들의 비해서 미숙하기 때문에 땅 세미나는 이 많았 인물이나 성 바닥 발바닥은 평소에도 식사를 하거나 조금 말 힘이 들어도 땀이 송골송골 맺히는 경우가 흔합니다 별다른 문제가 없어도 베개가 땀으로 젖는 경우도 있습니다 물론 감기에 걸리거나 다른 이상이 있는 경우에도 땅 조절하는 기능이 더 떨어져서 남을 과잉생산 하기도 합니다이들은 원래 땀이 많은 보입니다 그런데이가 땀을 많이 흘리면 몸이 허약하다 고 생각하는 부모들이 많은 것이 현실입니다기가 빔닌데도 땀을 많이 흘리니 까 몸이 허약하다 고 몸보신을 해줘야 한다고 말하는 부모도 있습니다 땀을 흘린다고 영양제 먹이는 부모도 많은 것이 현실입니다 부모들이 그렇게도 고민고민 하면서 운이 않은이들이 시킨 다음에 대해서 소청소에 가설은 별로 심각하게 생각하지 않습니다이가 땀을 많이 클리 더라도 열이 없고로 보기에 다른 이상이 없는 경우에는 대개 체계적인 경우라고 생각합니다 특히기가 어릴수록 땀을 많이 흘리게 되고 평소에 땀을 않으니 다가 갑자기 많이 흘리게 되는 경우도 많습니다이들 중에서도 특히 네이는 은니 식은땀을 많이 흘리는 법입니다 그런데 간혹 진짜 문제가 있는 경우도 있습니다 선천성 심장병이 있거나 갑상선 기능 항진증 처럼기의 체력을 소모시키는 병에 걸려도 땀을 많이 흘립니다 구루병 저혈당 수온 증도 핵 황달로 이란 4승 말이 내용 후에 점 같은 듣기만 해도 무시무시한 병들의 걸려도 땀을 많이 걸리지만 이름 병들은 원래 매우 드물고 요 다른 증상으로 병이 있는 것을 의심하지 땀을 많이 흘린다고 이름 병 대로의 심하지는 않습니다 예전에 영양이 부족하던 실 계획처럼 체력을 많이 소모시키는 병에 걸리면 땀을 많이 흘렸던 것은 사실입니다 하지만이들의 경우 결핵이 쉬운 땀이 오리니 되는 경우는 그 이 생각하기 힘듭니다 물론 남을 너무 많이 흘리거나 특정 부위에 땀이 지나치게 많은 경우는 한 번은 소아청소년과 의사 에게 보여서 다른 이상을 없는지 확인하는 것이 안전합니다 일반적으로는 담임니라도 다른 이상이 없다면 너무 걱정하지 말고 수분 충분히 섭취 시키고 잘 닦아주고 옷 자주 가입해서 채운 소실되지 않도록 신경 등 도 써주시면 된다는 거 알2시면 마음 편하실 겁니다 지금 땀 너무 걱정하지 마십시오'

In [37]:
eval_df['reference_title_caption'] = eval_df['reference_contexts'].map(
    lambda x: x[0].replace("title_caption: ", "").strip()
)

eval_df[['reference_title_caption', 'reference_contexts']].head(2)

,reference_title_caption,reference_contexts
0,[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 ...,[title_caption: [title] 식은땀! 이 정도는 알아두셔야 합니다. ...
1,[title] 식은땀! 이 정도는 알아두셔야 합니다. [caption] 안녕하세요 ...,[title_caption: [title] 식은땀! 이 정도는 알아두셔야 합니다. ...

In [38]:
eval_df = eval_df.merge(
    right=df[['video_url', 'title_caption']], how='inner',
    left_on="reference_title_caption", right_on="title_caption"
)

In [39]:
eval_df.rename(
    columns={
        "video_url": "reference_video_url"
    }, inplace= True
)

> 특정 단어들 제거

In [ ]:
for col in ["user_input", "reference"]:
    eval_df[col] = eval_df[col].map(
        lambda x: x.replace("삐뽀삐뽀119", "").replace("하정훈", "소아청소년").strip()
    )

In [40]:
eval_df[['user_input', 'reference', 'reference_video_url']].head()

,user_input,reference,reference_video_url
0,선천성 심장병이 있는 아동은 식은땀을 많이 흘릴 수 있나요?,"네, 선천성 심장병이 있는 아동은 땀을 많이 흘릴 수 있습니다. 이는 체력을 소모시...",https://www.youtube.com/watch?v=8GwNlF44ntY&li...
1,감기가 있는 어린이가 식은땀을 흘리는 이유는 무엇인가요?,감기에 걸리면 땀을 조절하는 기능이 떨어져서 땀을 과잉 생산할 수 있습니다. 특히 ...,https://www.youtube.com/watch?v=8GwNlF44ntY&li...
2,소아청소년과에서 식은땀에 대해 어떻게 설명하나요?,"소아청소년과 전문의는 식은땀에 대해, 아이들이 땀을 많이 흘리는 것은 정상적인 현상...",https://www.youtube.com/watch?v=8GwNlF44ntY&li...
3,감기와 관련하여 아이들이 식은땀을 많이 흘리는 이유는 무엇인가요?,"아이들은 땀을 조절하는 기능이 어른들에 비해 미숙하기 때문에, 평소에 땀을 많이 흘...",https://www.youtube.com/watch?v=8GwNlF44ntY&li...
4,황달이 땀과 관련이 있나요?,"황달은 드물게 땀을 많이 흘리는 원인 중 하나일 수 있지만, 일반적으로 땀을 많이 ...",https://www.youtube.com/watch?v=8GwNlF44ntY&li...

In [43]:
eval_df[['user_input', 'reference', 'reference_video_url']].tail()

,user_input,reference,reference_video_url
595,서 총선이란 뭐에요?,"서 총선은 돌치레와 관련된 개념으로, 아이들이 돌 즈음에 여러 가지 병에 걸리는 것...",https://www.youtube.com/watch?v=OHwlVtRkkfQ
596,소아과에서 돌치레가 무엇인지 설명해 줄 수 있나요?,"돌치레는 특정한 병을 말하는 것이 아니라, 아이들이 두 돌 세 돌 즈음에 걸릴 수 ...",https://www.youtube.com/watch?v=OHwlVtRkkfQ
597,"장미진이란 무엇이며, 돌치레와 어떤 관련이 있나요?","장미진은 돌발진이라고도 불리며, 돌치레의 일환으로 발생하는 질환입니다. 돌발진에 걸...",https://www.youtube.com/watch?v=OHwlVtRkkfQ
598,"소아과에서 돌치레라는 게 뭔지, 그리고 왜 애들이 돌치레를 겪는지 설명해 줄 수 있어요?","돌치레는 특정한 병을 말하는 것이 아니라, 어린이들이 여러 가지 병에 걸리는 것을 ...",https://www.youtube.com/watch?v=OHwlVtRkkfQ
599,"돌발진이란 무엇인지, 그리고 왜 부모들이 이 병에 대해 걱정하는지 설명해 줄 수 있나요?","돌발진은 특정한 병을 말하는 것이 아니라, 어린이들이 겪는 여러 가지 병을 통칭하는...",https://www.youtube.com/watch?v=OHwlVtRkkfQ

In [41]:
eval_df = eval_df[['user_input', 'reference', 'reference_video_url']]
print(f"befer: {eval_df.shape}")

eval_df.drop_duplicates(inplace=True, subset=['user_input', 'reference'])
print(f"after: {eval_df.shape}")

befer: (600, 3)
after: (599, 3)

### 저장하기

In [42]:
eval_df.to_csv("./data/training/illnesses.csv", index=False, header=True)